name = "mundial2026"
main = "worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

kv_namespaces = [
  { binding = "SORTEO_KV", id = "7041b2d5301647a1bf0abb1f08c262d0" }
]

[vars]
ADMIN_TOKEN = "Mundial2026"
